
###
# sing up

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "userName": "ysfgrl",
  "email": "ysfgrl@test.com",
  "firstName": "yusuf",
  "lastName": "Uğurlu",
  "password": "123456",
  "role": "admin",
  "profile": "minio://default"
}

###
# get token

GET http://localhost:8080/auth/signin?password=testd&username=ysfgrl

> {% client.global.set("auth_token", response.body.json.token); %}

###
# get token

POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "ysfgrl",
  "password": "123456"
}
> {% client.global.set("token", response.body.content.token); %}

###



###

GET http://localhost:8080/resources/list
Authorization: {{token}}

###

GET http://localhost:8080/resources/get/64dd7a3831779826103cb3ac


###

POST http://localhost:8080/resources/add
Content-Type: application/json

{
  "url": "http://testurl",
  "title": "test",
  "type": "image",
  "group": "Undefined",
  "task": "FaceDetect",
  "status": "created",
  "params": {
    "par": 1,
    "par2": ["tes", "ttt"]
  }
}