version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
  minio:
    image: minio/minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Admin123?
    volumes:
      - minioDB:/data
    command: server --console-address ":9001" /data
  api:
    container_name: api
    build:
      context: .
    depends_on:
      - mongodb
      - minio
      - redis
    ports:
      - "8080:8080"
volumes:
  mongodb:
  redisDB:
  minioDB: {}